### ISSUE TITLE
Good First Issue: Allow `initial_train_size` in `backtesting_forecaster` to accept date values

### ISSUE THREAD

**Issue by JavierEscobarOrtiz** [skforecast/skforecast#803]
Use branch `0.15.x` as base.

**Summary**

Currently, the `initial_train_size` parameter in the `backtesting_forecaster` function only accepts an integer value. This integer defines how many observations to use as the initial training set. We would like to extend this functionality so that `initial_train_size` can also accept a date (e.g., `'2020-01-01'`). If a date is provided, the function should calculate the appropriate number of observations corresponding to the time window between the start of the data and the given date.

**Task**  
1. Create an auxiliary function, `_preprocess_initial_train_size(y: pd.Series, initial_train_size)` in the `utils` module:

- `initial_train_size` can be an integer or any datetime format that pandas allows to be passed to a `pd.DatetimeIndex` (e.g., string, pandas timestamp...).
- If `y` does not have a `pd.DatetimeIndex` and `initial_train_size` is not an integer, raise a `TypeError` with the message: "If `y` does not have a pd.DatetimeIndex, `initial_train_size` must be an integer."
- If the series `y` has a `pd.DatetimeIndex`, this function will return the length of the time window between the start of the data and the given date as an integer value. The given date must be included in the window.
- If the input `initial_train_size` is an integer, return the same integer.
- Create unit tests using pytest in the `utils.tests` folder.

```python
# Expected behavior
# ==============================================================================
y = pd.Series([1, 2, 3, 4, 5], index=pd.date_range('2020-01-01', periods=5, freq='D'))
_preprocess_initial_train_size(y, '2020-01-02') # expected output: 2

y = pd.Series([1, 2, 3, 4, 5], index=pd.date_range('2020-01-01', periods=5, freq='D'))
_preprocess_initial_train_size(y, 2) # expected output: 2

y = pd.Series([1, 2, 3, 4, 5], index=pd.RangeIndex(start=0, stop=5, step=1))
_preprocess_initial_train_size(y, '2020-01-02') # expected output: TypeError
```

2. Integrate this function with `_backtesting_forecasting` and  `backtesting_forecasting` in the `model_selection` module.

**Acceptance Criteria**
- [ ] The `initial_train_size` parameter accepts both integer and date formats.
- [ ] The function correctly calculates the initial training size when a date is provided.
- [ ] Existing tests continue to pass.
- [ ] New test cases are added to verify the correct behavior for both int and date inputs.

**Full Example**

The initial training set must contain 127 observations and the results must be the same if `initial_train_size = 127`.

```python
# Expected behavior
# ==============================================================================
data = fetch_dataset(name="h2o", kwargs_read_csv={"names": ["y", "datetime"], "header": 0})
initial_train_size = '2002-01-01 00:00:00'

forecaster = ForecasterRecursive(
                 regressor = LGBMRegressor(random_state=123, verbose=-1),
                 lags      = 15 
             )

cv = TimeSeriesFold(
         steps                 = 10,
         initial_train_size    = initial_train_size,
         refit                 = False,
         fixed_train_size      = False,
         gap                   = 0,
         allow_incomplete_fold = True
     )

metric, predictions = backtesting_forecaster(
                          forecaster            = forecaster,
                          cv                    = cv,
                          y                     = data['y'],
                          metric                = 'mean_squared_error',
                          verbose               = True,
                          show_progress         = True  
                      )
```

**Comment by IamjustNick** [comment]
We will take this for the Hacktoberfest organised by Pydata along with @Lt-Serge and @laseiras

**Comment by g-rubio** [comment]
One question @JavierEscobarOrtiz : as initial_train_size is not a parameter of backtesting_forecaster, why isn't the function added in the Fold classes? For instance, this docstring needs to be changed right?: https://github.com/skforecast/skforecast/blob/88da967670344453cdc1ab775e4c228cdc394617/skforecast/model_selection/_split.py#L27

**Comment by JavierEscobarOrtiz** [comment]
@g-rubio is taking this issue

**Update**

As part of skforecast `0.14.0`, `initial_train_size` is now an argument of `BaseFold`, `TimeSeriesFold` and `OneStepAheadFold`.

**Tasks**

- Fork the skforecast 0.15.x branch with the latest update.

- Modify methods `_validate_params` in `BaseFold` and `split` in `TimeSeriesFold` and `OneStepAheadFold` to work when `initial_train_size` is a date.

- `_validate_params` in `BaseFold` contains the checks for the parameters. Extend for `initial_train_size` as date. See the `date_to_index_position` function from `utils`. This function is used when `steps` is a date in the predict method of the `ForecasterRecursive`.

- `split` must use the `date_to_index_position` function from `utils` to convert `initial_train_size` to an `integer`. I suggest using this function to overwrite the attribute `self.initial_train_size` when it is not an int during the `split` method.

- Create the corresponding tests for the 3 classes

**Comment by g-rubio** [comment]
@JavierEscobarOrtiz 
> split must use the date_to_index_position function from utils to convert initial_train_size to an integer. I suggest using this function to overwrite the attribute self.initial_train_size when it is not an int during the split method.

I think I can't use `date_to_index_position` because of the following condition:
https://github.com/skforecast/skforecast/blob/dce50012d176b143cda745201b2d8da110be3cce/skforecast/utils/utils.py#L1600C9-L1605C14

For this new feature, the target date must be before the last date to be part of the training set. I don't know if changing this check is appropriate

**Comment by JavierEscobarOrtiz** [comment]
That’s true. Include a new argument in the function, called “method”, that can be ‘validation’ or ‘predict’ to create an if statement and avoid this check. As default, this argument must be “predict”

**Comment by g-rubio** [comment]
Hi @JavierEscobarOrtiz, I'm ready to create a pull request, but I have one problem. All tests related to the code I changed run successfully, but some of the rest fail or I can't run them. I'm not entirely sure why, I think the failures are related to my setup not being correct, but I want to ask if this is ok or if I should revise all tests more carefully. For instance, I'm having issues with the deep_learning ones.

Btw, I looked in the [contributing guide here](https://github.com/skforecast/skforecast/blob/88da967670344453cdc1ab775e4c228cdc394617/CONTRIBUTING.md), it is suggested to install the requirements in requirements_test.txt. But that file is no longer in the repo I think. 

This has been fun, i learned a lot by looking at the insides of skforecast  😄

**Comment by JavierEscobarOrtiz** [comment]
Hi @g-rubio 

Nice!! Don't worry about the testing. Create the PR, but change the target branch to `feature_initial_train_size_as_date` instead of `0.15.x`. I will check the tests and if I see anything wrong I will let you know.

Thanks for checking the contributor guide, I have updated it. The requirements are now in the `pyproject.toml` file under the `test` label.
